const allQuestions = [
  {q:"Comment dit-on 'Novembre' en anglais ?", a:["October","November","December","September"], correct:1},
  {q:"Comment dit-on 'Samedi' en anglais ?", a:["Sunday","Saturday","Friday","Monday"], correct:1},
  {q:"Comment dit-on 'Septembre' en anglais ?", a:["September","June","August","May"], correct:0},
  {q:"Comment dit-on 'Mardi' en anglais ?", a:["Wednesday","Tuesday","Thursday","Friday"], correct:1},
  {q:"Comment dit-on 'Huit' en anglais ?", a:["Seven","Nine","Eight","Six"], correct:2},
  {q:"Comment dit-on 'Dix-sept' en anglais ?", a:["Seventeen","Fifteen","Fourteen","Sixteen"], correct:0},
  {q:"Comment dit-on 'Trente' en anglais ?", a:["Thirty","Twenty","Thirty-five","Forty"], correct:0},
  {q:"Comment dit-on 'Mille' en anglais ?", a:["Ten thousand","Thousand","Hundred","Million"], correct:1},
  {q:"Comment dit-on 'Rouge' en anglais ?", a:["Blue","Green","Red","Yellow"], correct:2},
  {q:"Comment dit-on 'Vert' en anglais ?", a:["Yellow","Green","Blue","Red"], correct:1},
  {q:"Comment dit-on 'Bleu' en anglais ?", a:["Blue","Black","Pink","White"], correct:0},
  {q:"Comment dit-on 'Orange' en anglais ?", a:["Orange","Purple","Red","Brown"], correct:0},
  {q:"Comment dit-on 'Printemps' en anglais ?", a:["Autumn","Winter","Spring","Summer"], correct:2},
  {q:"Comment dit-on 'Hiver' en anglais ?", a:["Winter","Spring","Summer","Autumn"], correct:0},
  {q:"Comment dit-on 'Été' en anglais ?", a:["Spring","Summer","Winter","Autumn"], correct:1},
  {q:"Comment dit-on 'Automne' en anglais ?", a:["Summer","Winter","Spring","Autumn"], correct:3},
  {q:"Comment dit-on 'Tête' en anglais ?", a:["Head","Hand","Foot","Leg"], correct:0},
  {q:"Comment dit-on 'Main' en anglais ?", a:["Foot","Hand","Head","Arm"], correct:1},
  {q:"Comment dit-on 'Pied' en anglais ?", a:["Leg","Foot","Hand","Head"], correct:1},
  {q:"Comment dit-on 'Jambe' en anglais ?", a:["Arm","Foot","Leg","Hand"], correct:2},
  {q:"Comment dit-on 'Bleu clair' en anglais ?", a:["Light blue","Dark blue","Blue","Sky blue"], correct:0},
  {q:"Comment dit-on 'Deux mille' en anglais ?", a:["Two thousand","Two hundred","Twenty","Two million"], correct:0},
  {q:"Comment dit-on 'Quarante-cinq' en anglais ?", a:["Forty-five","Fifty-five","Forty","Thirty-five"], correct:0},
  {q:"Comment dit-on 'Vendredi' en anglais ?", a:["Thursday","Friday","Tuesday","Wednesday"], correct:1},
  {q:"Comment dit-on 'Dimanche' en anglais ?", a:["Sunday","Monday","Saturday","Friday"], correct:0},
  {q:"Comment dit-on 'Lundi' en anglais ?", a:["Monday","Tuesday","Sunday","Wednesday"], correct:0},
  {q:"Comment dit-on 'Jeudi' en anglais ?", a:["Wednesday","Thursday","Tuesday","Friday"], correct:1},
  {q:"Comment dit-on 'Cent' en anglais ?", a:["Hundred","Thousand","Million","Ten"], correct:0},
  {q:"Comment dit-on 'Quinze' en anglais ?", a:["Fifteen","Fourteen","Sixteen","Seventeen"], correct:0},
  {q:"Comment dit-on 'Bleu foncé' en anglais ?", a:["Dark blue","Light blue","Blue","Navy"], correct:0},
  {q:"Comment dit-on 'Rose' en anglais ?", a:["Pink","Red","Orange","Purple"], correct:0},
  {q:"Comment dit-on 'Corps' en anglais ?", a:["Body","Head","Hand","Foot"], correct:0},
  {q:"Comment dit-on 'Bras' en anglais ?", a:["Arm","Leg","Hand","Foot"], correct:0},
  {q:"Comment dit-on 'Mille cinq cents' en anglais ?", a:["One thousand five hundred","One thousand five","Five hundred","One hundred fifty"], correct:0},
];

// Fonction pour tirer au hasard sans doublon
function
